
name: Static Release Build

on: [push]

permissions:
  contents: write


jobs:
  Linux-Cross-Compile:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ubuntu-latest
    container:
      image: muslcc/x86_64:${{ matrix.arch }}-linux-musl
      options: --user root
    steps:
      - uses: actions/checkout@v3

      - name: Add build dependencies
        run: |
          apk add --update --no-cache --no-progress bash make curl tar libpcap-dev
      
      - name: Compile-${{ matrix.arch }}
        run: |
          gcc -Wall -O2 -static -o dnsstream dnsstream.c -lpcap
          strip dnsstream
          mv dnsstream dnsstream_linux-${{ matrix.arch }}
      
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: $${{ secrets.GITHUB_TOKEN }}
          file: dnsstream_linux-${{ matrix.arch }}
          overwrite: true