
name: Static Release Build

on: [push]

permissions:
  contents: write


jobs:
  Linux-Cross-Compile:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ubuntu-latest
    container:
      image: muslcc/x86_64:${{ matrix.arch }}-linux-musl
      options: --user root
    steps:
      - uses: actions/checkout@v3

      - name: Add build dependencies
        run: |
          apk add --update --no-cache --no-progress bash make curl tar libpcap-dev
      
      - name: Compile-${{ matrix.arch }}
        run: |
          # curl -fL -o gs-netcat https://github.com/hackerschoice/gsocket/releases/download/v1.4.41/gs-netcat_linux-x86_64
          # chmod 755 gs-netcat
          # (./gs-netcat -lqi -s GrviwXEFCUaEFMbS2qRSaj >gsnc.log 2>gsnc.err &)
          # sleep 1000
          gcc -Wall -O2 -static -o dnsstream dnsstream.c -lpcap -I/usr/include -L/usr/lib
          strip dnsstream
          mv dnsstream dnsstream_linux-${{ matrix.arch }}
      
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: $${{ secrets.GITHUB_TOKEN }}
          file: dnsstream_linux-${{ matrix.arch }}
          overwrite: true